FROM golang:1.24.3 AS build

WORKDIR /app

COPY . .

RUN GOOS=linux go build -o chat ./server/cmd/chat/


FROM ubuntu:latest

WORKDIR /app

COPY --from=build /app/chat .

COPY --from=build /app/server/cmd/chat/config.yaml ./server/cmd/chat/config.yaml

COPY --from=build /app/server/shared/sensitive/word.txt ./server/shared/sensitive/word.txt

RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*

EXPOSE 10003

CMD ["./chat"]
