// Code generated by Kitex v0.13.1. DO NOT EDIT.

package quizservice

import (
	"context"
	"errors"
	quiz "github.com/Rinai-R/ApexLecture/server/shared/kitex_gen/quiz"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"submitQuestion": kitex.NewMethodInfo(
		submitQuestionHandler,
		newQuizServiceSubmitQuestionArgs,
		newQuizServiceSubmitQuestionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"submitAnswer": kitex.NewMethodInfo(
		submitAnswerHandler,
		newQuizServiceSubmitAnswerArgs,
		newQuizServiceSubmitAnswerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	quizServiceServiceInfo                = NewServiceInfo()
	quizServiceServiceInfoForClient       = NewServiceInfoForClient()
	quizServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return quizServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return quizServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return quizServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "QuizService"
	handlerType := (*quiz.QuizService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "quiz",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func submitQuestionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*quiz.QuizServiceSubmitQuestionArgs)
	realResult := result.(*quiz.QuizServiceSubmitQuestionResult)
	success, err := handler.(quiz.QuizService).SubmitQuestion(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQuizServiceSubmitQuestionArgs() interface{} {
	return quiz.NewQuizServiceSubmitQuestionArgs()
}

func newQuizServiceSubmitQuestionResult() interface{} {
	return quiz.NewQuizServiceSubmitQuestionResult()
}

func submitAnswerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*quiz.QuizServiceSubmitAnswerArgs)
	realResult := result.(*quiz.QuizServiceSubmitAnswerResult)
	success, err := handler.(quiz.QuizService).SubmitAnswer(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQuizServiceSubmitAnswerArgs() interface{} {
	return quiz.NewQuizServiceSubmitAnswerArgs()
}

func newQuizServiceSubmitAnswerResult() interface{} {
	return quiz.NewQuizServiceSubmitAnswerResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SubmitQuestion(ctx context.Context, request *quiz.SubmitQuestionRequest) (r *quiz.SubmitQuestionResponse, err error) {
	var _args quiz.QuizServiceSubmitQuestionArgs
	_args.Request = request
	var _result quiz.QuizServiceSubmitQuestionResult
	if err = p.c.Call(ctx, "submitQuestion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SubmitAnswer(ctx context.Context, request *quiz.SubmitAnswerRequest) (r *quiz.SubmitAnswerResponse, err error) {
	var _args quiz.QuizServiceSubmitAnswerArgs
	_args.Request = request
	var _result quiz.QuizServiceSubmitAnswerResult
	if err = p.c.Call(ctx, "submitAnswer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
