// Code generated by hertz generator.

package lecture

import (
	"context"
	"strconv"

	base "github.com/Rinai-R/ApexLecture/server/cmd/api/biz/model/base"
	lecture "github.com/Rinai-R/ApexLecture/server/cmd/api/biz/model/lecture"
	"github.com/Rinai-R/ApexLecture/server/cmd/api/config"
	rpc "github.com/Rinai-R/ApexLecture/server/shared/kitex_gen/lecture"
	"github.com/Rinai-R/ApexLecture/server/shared/rsp"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateLecture .
// @router lecture/ [POST]
func CreateLecture(ctx context.Context, c *app.RequestContext) {
	var err error
	var req lecture.StartRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, rsp.ErrorParameterError())
		return
	}
	id, ok := c.Params.Get("id")
	if !ok {
		c.JSON(consts.StatusBadRequest, rsp.ErrorParameterError())
		return
	}
	hostid, _ := strconv.ParseInt(id, 10, 64)
	resp, _ := config.LectureClient.Start(ctx, &rpc.StartRequest{
		HostId:      hostid,
		Title:       req.Title,
		Description: req.Description,
		Speaker:     req.Speaker,
		Sdp:         req.Sdp,
	})
	switch resp.Response.Code {
	case rsp.Success:
		c.JSON(consts.StatusOK, resp)
	default:
		c.JSON(consts.StatusBadRequest, resp)
	}
}

// AttendLecture .
// @router lecture/:roomid/attend [POST]
func AttendLecture(ctx context.Context, c *app.RequestContext) {
	var err error
	var req lecture.AttendRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.BaseResponse)

	c.JSON(consts.StatusOK, resp)
}

// Inroom .
// @router lecture/:roomid/ws [GET]
// websocket 连接到聊天室，包括聊天，问题等服务。
func Inroom(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.NilResponse
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}

// StartLecture .
// @router lecture/ [POST]
func StartLecture(ctx context.Context, c *app.RequestContext) {
	var err error
	var req lecture.StartRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(lecture.StartResponse)

	c.JSON(consts.StatusOK, resp)
}
