// Code generated by hertz generator.

package quiz

import (
	"github.com/Rinai-R/ApexLecture/server/cmd/api/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.JwtAuth,
	}
}

func _quizMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roomidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitanswerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitquestionMw() []app.HandlerFunc {
	// your code...
	return nil
}
