// Code generated by hertz generator.

package lecture

import (
	"github.com/Rinai-R/ApexLecture/server/cmd/api/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JwtAuth,
	}
}

func _lectureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createlectureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roomidMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.ConsistenceHashStoreKey,
	}
}

func _attendlectureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _offerlectureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _inroomMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startlectureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _attendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recordlectureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethistorylectureMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _randomselectMw() []app.HandlerFunc {
	// your code...
	return nil
}
