FROM golang:1.24.3 AS build

WORKDIR /app

COPY . .

RUN GOOS=linux go build -o push ./server/cmd/push/


FROM ubuntu:latest

WORKDIR /app

COPY --from=build /app/push .

COPY --from=build /app/server/cmd/push/config.yaml ./server/cmd/push/config.yaml

COPY --from=build /app/server/shared/sensitive/word.txt ./server/shared/sensitive/word.txt

RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*

EXPOSE 10004

CMD ["./push"]
