// Code generated by hertz generator.

package chat

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chat0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
