// Code generated by hertz generator.

package agent

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roomidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _askMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsummaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startsummaryMw() []app.HandlerFunc {
	// your code...
	return nil
}
