// Code generated by hertz generator.

package user

import (
	"context"

	user "github.com/Rinai-R/ApexLecture/server/cmd/api/biz/model/user"
	"github.com/Rinai-R/ApexLecture/server/shared/rsp"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, rsp.ErrorUsernameOrPasswordLength())
		return
	}

	c.JSON(consts.StatusOK, nil)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, rsp.ErrorUsernameOrPasswordLength())
		return
	}

	c.JSON(consts.StatusOK, nil)
}
