FROM golang:1.24.3 AS build

WORKDIR /app

COPY . .

RUN GOOS=linux go build -o agent ./server/cmd/agent/


FROM ubuntu:latest

WORKDIR /app

COPY --from=build /app/agent .

COPY --from=build /app/server/cmd/agent/config.yaml ./server/cmd/agent/config.yaml

COPY --from=build /app/server/shared/sensitive/word.txt ./server/shared/sensitive/word.txt

RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*

EXPOSE 10006

CMD ["./agent"]
