// Code generated by Kitex v0.13.1. DO NOT EDIT.

package agentservice

import (
	"context"
	"errors"
	agent "github.com/Rinai-R/ApexLecture/server/shared/kitex_gen/agent"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ask": kitex.NewMethodInfo(
		askHandler,
		newAgentServiceAskArgs,
		newAgentServiceAskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"startSummary": kitex.NewMethodInfo(
		startSummaryHandler,
		newAgentServiceStartSummaryArgs,
		newAgentServiceStartSummaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"getSummary": kitex.NewMethodInfo(
		getSummaryHandler,
		newAgentServiceGetSummaryArgs,
		newAgentServiceGetSummaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	agentServiceServiceInfo                = NewServiceInfo()
	agentServiceServiceInfoForClient       = NewServiceInfoForClient()
	agentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return agentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return agentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return agentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AgentService"
	handlerType := (*agent.AgentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "agent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func askHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceAskArgs)
	realResult := result.(*agent.AgentServiceAskResult)
	success, err := handler.(agent.AgentService).Ask(ctx, realArg.AskRequest)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceAskArgs() interface{} {
	return agent.NewAgentServiceAskArgs()
}

func newAgentServiceAskResult() interface{} {
	return agent.NewAgentServiceAskResult()
}

func startSummaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceStartSummaryArgs)
	realResult := result.(*agent.AgentServiceStartSummaryResult)
	success, err := handler.(agent.AgentService).StartSummary(ctx, realArg.SummaryRequest)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceStartSummaryArgs() interface{} {
	return agent.NewAgentServiceStartSummaryArgs()
}

func newAgentServiceStartSummaryResult() interface{} {
	return agent.NewAgentServiceStartSummaryResult()
}

func getSummaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceGetSummaryArgs)
	realResult := result.(*agent.AgentServiceGetSummaryResult)
	success, err := handler.(agent.AgentService).GetSummary(ctx, realArg.SummaryRequest)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceGetSummaryArgs() interface{} {
	return agent.NewAgentServiceGetSummaryArgs()
}

func newAgentServiceGetSummaryResult() interface{} {
	return agent.NewAgentServiceGetSummaryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Ask(ctx context.Context, askRequest *agent.AskRequest) (r *agent.AskResponse, err error) {
	var _args agent.AgentServiceAskArgs
	_args.AskRequest = askRequest
	var _result agent.AgentServiceAskResult
	if err = p.c.Call(ctx, "ask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartSummary(ctx context.Context, summaryRequest *agent.StartSummaryRequest) (r *agent.StartSummaryResponse, err error) {
	var _args agent.AgentServiceStartSummaryArgs
	_args.SummaryRequest = summaryRequest
	var _result agent.AgentServiceStartSummaryResult
	if err = p.c.Call(ctx, "startSummary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSummary(ctx context.Context, summaryRequest *agent.GetSummaryRequest) (r *agent.GetSummaryResponse, err error) {
	var _args agent.AgentServiceGetSummaryArgs
	_args.SummaryRequest = summaryRequest
	var _result agent.AgentServiceGetSummaryResult
	if err = p.c.Call(ctx, "getSummary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
