// Code generated by hertz generator.

package push

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _receiveMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _receive0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
