FROM golang:1.24.3 AS build

WORKDIR /app

COPY . .

RUN GOOS=linux go build -o lecture ./server/cmd/lecture/


FROM ubuntu:latest

WORKDIR /app

COPY --from=build /app/lecture .

COPY --from=build /app/server/cmd/lecture/config.yaml ./server/cmd/lecture/config.yaml

COPY --from=build /app/server/shared/sensitive/word.txt ./server/shared/sensitive/word.txt

RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*

EXPOSE 10002

CMD ["./lecture"]
