// Code generated by Kitex v0.13.1. DO NOT EDIT.

package lectureservice

import (
	"context"
	"errors"
	lecture "github.com/Rinai-R/ApexLecture/server/shared/kitex_gen/lecture"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"createLecture": kitex.NewMethodInfo(
		createLectureHandler,
		newLectureServiceCreateLectureArgs,
		newLectureServiceCreateLectureResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"attend": kitex.NewMethodInfo(
		attendHandler,
		newLectureServiceAttendArgs,
		newLectureServiceAttendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	lectureServiceServiceInfo                = NewServiceInfo()
	lectureServiceServiceInfoForClient       = NewServiceInfoForClient()
	lectureServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return lectureServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return lectureServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return lectureServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LectureService"
	handlerType := (*lecture.LectureService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "lecture",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func createLectureHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*lecture.LectureServiceCreateLectureArgs)
	realResult := result.(*lecture.LectureServiceCreateLectureResult)
	success, err := handler.(lecture.LectureService).CreateLecture(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLectureServiceCreateLectureArgs() interface{} {
	return lecture.NewLectureServiceCreateLectureArgs()
}

func newLectureServiceCreateLectureResult() interface{} {
	return lecture.NewLectureServiceCreateLectureResult()
}

func attendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*lecture.LectureServiceAttendArgs)
	realResult := result.(*lecture.LectureServiceAttendResult)
	success, err := handler.(lecture.LectureService).Attend(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLectureServiceAttendArgs() interface{} {
	return lecture.NewLectureServiceAttendArgs()
}

func newLectureServiceAttendResult() interface{} {
	return lecture.NewLectureServiceAttendResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateLecture(ctx context.Context, request *lecture.CreareLectureRequest) (r *lecture.CreareLectureResponse, err error) {
	var _args lecture.LectureServiceCreateLectureArgs
	_args.Request = request
	var _result lecture.LectureServiceCreateLectureResult
	if err = p.c.Call(ctx, "createLecture", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Attend(ctx context.Context, request *lecture.AttendRequest) (r *lecture.AttendResponse, err error) {
	var _args lecture.LectureServiceAttendArgs
	_args.Request = request
	var _result lecture.LectureServiceAttendResult
	if err = p.c.Call(ctx, "attend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
