// Code generated by hertz generator.

package push

import (
	"context"

	push "github.com/Rinai-R/ApexLecture/server/cmd/api/biz/model/push"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Receive .
// @router /receive/:roomid [GET]
func Receive(ctx context.Context, c *app.RequestContext) {
	var err error
	var req push.PushQuestionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(push.PushMessageResponse)

	c.JSON(consts.StatusOK, resp)
}
