name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.3'

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: |
          go vet -stdmethods=false $(go list ./...)
      - name: start
        run: |
          make up
          nohup make hz-run > server.log 2>&1 &
          sleep 10

      - name: Test
        run: go test -v ./...
