name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.3'

      - name: Download dependencies
        run: go mod download

      - name: Vet
        run: |
          go vet -stdmethods=false $(go list ./...)
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Format
        run: |
          go install mvdan.cc/gofumpt@v0.2.0
          test -z "$(gofumpt -l -extra .)"
