name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.3'

          
      - name: Download dependencies
        run: go mod download

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          docker --version

      - name: Install Docker Compose
        run: |
          COMPOSE_VERSION="1.29.2"
          sudo curl -L "https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start services
        run: |
          make up
          nohup make hz-run > server.log 2>&1 &
          sleep 10

      - name: Run tests
        run: go test -v ./...
